### ISSUE TITLE
some video's width and height are wrong after compressed

### ISSUE THREAD

**Issue by kingty** [lalongooo/video-compressor#23]
i don't know why

**Comment by lalongooo** [comment]
What API version are you testing against?

**Comment by yanglufei** [comment]
The width and height of the original video is written backwards

**Comment by yanglufei** [comment]
Write the inverse

**Comment by SimranChawla1995** [comment]
Writing inverse in original width & height is also not resulting in correct video resolution after compression.
Have you found out its solution ?? Please help.

**Comment by SimranChawla1995** [comment]
I've tested its compression using telegram app. It's  giving correct result there. Check the screenshots.
![screenshot_20190117-115522](https://user-images.githubusercontent.com/31208270/51299628-21019080-1a4f-11e9-8d80-dab689d4a974.png) - via telegram

![screenshot_20190117-115534](https://user-images.githubusercontent.com/31208270/51299630-252dae00-1a4f-11e9-9b41-2d701303ceaf.png) - via this library code.
@lalongooo please show some light on this issue.

**Comment by SimranChawla1995** [comment]
I've developed a workaround for this by changing result height and width with respect to original height and width. I'm not sure if telegram doing the same.
